=== MatthieuParme/media-cloud-ai.github.com/standard/1.0/workflow-definition.schema.json
{
    "$id": "https://media-cloud.ai/standard/1.0/workflow-definition.schema.json",
    "$schema": "http://json-schema.org/draft-04/schema#",
    "definitions": {
        "start_parameter": {
            "type": "object",
            "properties": {
                "id": {
                    "pattern": "^(.*)$",
                    "title": "Identifier of the parameter",
                    "type": "string"
                },
                "label": {
                    "pattern": "^(.*)$",
                    "title": "Label of the parameter",
                    "type": "string"
                },
                "type": {
                    "pattern": "^(.*)$",
                    "title": "Type of the data value for this parameter",
                    "type": "string",
                    "enum": [
                        "file",
                        "choice",
                        "number"
                    ]
                },
                "default": {
                    "pattern": "^(.*)$",
                    "title": "Default value of the parameter",
                    "type": [
                        "integer",
                        "number",
                        "string",
                        "array"
                    ]
                },
                "value": {
                    "pattern": "^(.*)$",
                    "title": "Value of the parameter",
                    "type": [
                        "integer",
                        "number",
                        "string",
                        "array"
                    ]
                },
                "required": {
                    "default": false,
                    "title": "Set the parameter required",
                    "type": "boolean"
                }
            },
            "required": [
                "id",
                "label",
                "type"
            ]
        },
        "parameter": {
            "type": "object",
            "properties": {
                "id": {
                    "pattern": "^(.*)$",
                    "title": "Identifier of the parameter",
                    "type": "string"
                },
                "type": {
                    "pattern": "^(.*)$",
                    "title": "Type of the data value for this parameter",
                    "type": "string",
                    "enum": [
                        "array_of_strings",
                        "array_of_templates",
                        "boolean",
                        "credential",
                        "filter",
                        "integer",
                        "requirements",
                        "select_input",
                        "string",
                        "template"
                    ]
                },
                "default": {
                    "pattern": "^(.*)$",
                    "title": "Default value of the parameter",
                    "type": [
                        "boolean",
                        "number",
                        "integer",
                        "string",
                        "array",
                        "object"
                    ]
                },
                "value": {
                    "pattern": "^(.*)$",
                    "title": "Value of the parameter",
                    "type": [
                        "boolean",
                        "number",
                        "integer",
                        "string",
                        "array",
                        "object"
                    ]
                }
            },
            "required": [
                "id",
                "type",
                "value"
            ]
        },
        "step": {
            "type": "object",
            "properties": {
                "enable": {
                    "default": false,
                    "examples": [
                        true
                    ],
                    "title": "The Enable Schema",
                    "type": "boolean"
                },
                "icon": {
                    "examples": [
                        "file_download"
                    ],
                    "pattern": "^(.*)$",
                    "title": "The Icon Schema",
                    "type": "string"
                },
                "id": {
                    "default": 0,
                    "examples": [
                        0
                    ],
                    "title": "The Id Schema",
                    "type": "integer"
                },
                "label": {
                    "examples": [
                        "Download source elements"
                    ],
                    "pattern": "^(.*)$",
                    "title": "The Label Schema",
                    "type": "string"
                },
                "name": {
                    "examples": [
                        "job_transfer"
                    ],
                    "pattern": "^([a-z_]+)$",
                    "title": "Name of the parameter",
                    "type": "string"
                },
                "parameters": {
                    "$ref": "#/definitions/parameters"
                },
                "parent_ids": {
                    "title": "Reference(s) of parent steps",
                    "type": "array",
                    "items": { "type": "integer" }
                },
                "required": {
                    "title": "Reference(s) of required steps to run that step",
                    "type": "array",
                    "items": { "type": "integer" }
                }
            },
            "required": [
                "id",
                "name",
                "label",
                "icon",
                "parameters"
            ],
            "title": "The Items Schema"
        },
        "tag": {
            "type": "string",
            "examples": [
                "speech_to_text"
            ],
            "pattern": "^(.*)$",
            "title": "The Items Schema"
        },
        "parameters":{
            "type":	"array",
            "items":{ "$ref": "#/definitions/parameter" },
            "title": "Array of Parameter"
        }
    },
    "properties": {
        "identifier": {
            "examples": [
                "speech_to_text"
            ],
            "pattern": "^([a-z_]+)$",
            "title": "The Identifier of the workflow, used to reference it",
            "type": "string"
        },
        "label": {
            "$id": "#/properties/label",
            "examples": [
                "speech_to_text"
            ],
            "pattern": "^(.*)$",
            "title": "The label of the workflow, used as displayed name",
            "type": "string"
        },
        "icon": {
            "examples": [
                "subtitles"
            ],
            "pattern": "^([a-z_]+)$",
            "title": "The icon used with the label. One of https://material.io/resources/icons/",
            "type": "string"
        },
        "start_parameters": {
            "items": { "$ref": "#/definitions/start_parameter" },
            "title": "Definition of available parameters to start the workflow definition",
            "type": "array"
        },
        "parameters": {
            "items": { "$ref": "#/definitions/parameter" },
            "title": "Storage of dynamic parameters during process of the workflow instance",
            "type": "array"
        },
        "steps": {
            "items": { "$ref": "#/definitions/step" },
            "title": "Steps to represent the complete process",
            "type": "array"
        },
        "tags": {
            "items": {"$ref": "#/definitions/tag" },
            "title": "List of tags to classify the worklow",
            "type": "array"
        },
        "version_major": {
            "title": "Major version of this Workflow definition",
            "type": "integer"
        },
        "version_minor": {
            "title": "Minor version of this Workflow definition",
            "type": "integer"
        },
        "version_micro": {
            "title": "Micro version of this Workflow definition",
            "type": "integer"
        }
    },
    "required": [
        "identifier",
        "label",
        "icon",
        "version_major",
        "version_minor",
        "version_micro",
        "tags",
        "parameters",
        "steps"
    ],
    "title": "Schema of Workflow Definition for Media Cloud AI",
    "type": "object"
}

=== MatthieuParme/media-cloud-ai.github.com/tests/validate-json-schema/workflow-definition-test.json
{
    "icon": "tete_a_toto",
    "identifier": "monsieur_toto",
    "label": "",
    "parameters": [],
    "start_parameters": [
        {
            "accept": ".veg",
            "id": "vegetable_name",
            "label": "Vegetable",
            "type": "file"
        }
    ],
    "steps": [
        {
            "enable": true,
            "icon": "clean_vegies",
            "id": 0,
            "label": "Clean vegetables",
            "name": "clean",
            "parameters": [
                {
                    "id": "name",
                    "type": "string",
                    "value": "{vegetable_name}"
                }
            ]
        },
        {
            "enable": true,
            "icon": "cook_vegies",
            "id": 0,
            "label": "Cook vegetables",
            "name": "cook",
            "parameters": [
                {
                    "id": "name",
                    "type": "string",
                    "value": "{vegetable_name}"
                }
            ],
            "parent_ids": [
                0
            ],
            "required": [
                0
            ]
        }
    ],
    "tags": [
        "toto"
    ],
    "version_major": 0,
    "version_micro": 1,
    "version_minor": 0
}
